# Generated by Django 5.2.7 on 2025-11-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
