# Generated by Django 5.2.7 on 2025-11-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicionEnergetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.CharField(max_length=80)),
                ('equipo', models.CharField(blank=True, max_length=80)),
                ('fecha', models.DateTimeField()),
                ('potencia_kw', models.DecimalField(decimal_places=3, max_digits=8)),
                ('energia_kwh', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ubicacion', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Medición energética',
                'verbose_name_plural': 'Mediciones energéticas',
            },
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
