# Generated by Django 5.2.7 on 2025-11-25 23:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_empleado_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicionenergetica',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicionenergetica',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mediciones'),
        ),
    ]
