# Generated by Django 5.2.7 on 2025-11-27 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='fecha',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(default='Sin asunto', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
